// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQ9Vg0hOxUYCas7i2NzBb8ir1ZfVfnhU',
    appId: '1:1031540536083:web:93c9fa77ed6a85476de0e6',
    messagingSenderId: '1031540536083',
    projectId: 'tudoapp-f1cef',
    authDomain: 'tudoapp-f1cef.firebaseapp.com',
    storageBucket: 'tudoapp-f1cef.firebasestorage.app',
    measurementId: 'G-8PZDZFXM8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmH9drlzpy-h7Nst54-FWE4jVNmIDPws',
    appId: '1:1031540536083:android:3e3b15ba3766b12b6de0e6',
    messagingSenderId: '1031540536083',
    projectId: 'tudoapp-f1cef',
    storageBucket: 'tudoapp-f1cef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYaBM9-o6VyMUQLiwQH1dXzxIZkL-HPSo',
    appId: '1:1031540536083:ios:96049f726f857db26de0e6',
    messagingSenderId: '1031540536083',
    projectId: 'tudoapp-f1cef',
    storageBucket: 'tudoapp-f1cef.firebasestorage.app',
    iosBundleId: 'com.example.tudoAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYaBM9-o6VyMUQLiwQH1dXzxIZkL-HPSo',
    appId: '1:1031540536083:ios:96049f726f857db26de0e6',
    messagingSenderId: '1031540536083',
    projectId: 'tudoapp-f1cef',
    storageBucket: 'tudoapp-f1cef.firebasestorage.app',
    iosBundleId: 'com.example.tudoAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiQ9Vg0hOxUYCas7i2NzBb8ir1ZfVfnhU',
    appId: '1:1031540536083:web:183779181d4ba34e6de0e6',
    messagingSenderId: '1031540536083',
    projectId: 'tudoapp-f1cef',
    authDomain: 'tudoapp-f1cef.firebaseapp.com',
    storageBucket: 'tudoapp-f1cef.firebasestorage.app',
    measurementId: 'G-ZJ3EGBXW1D',
  );
}
